name: Docker Image CI

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mipro:latest
      -  
        name: connect ssh
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop ${{ secrets.CNAME }}
            docker rm ${{ secrets.CNAME }}
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/mipro
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mipro
            docker run --name ${{ secrets.CNAME }} -p 8000:8000 -d -e DB_HOST=${{secrets.DB_HOST}} -e DB_PORT=3306 -e DB_USER=${{secrets.DB_USER}} -e DB_NAME=${{secrets.DB_NAME}} -e DB_PASS=${{secrets.DB_PASS}} -e USER_SECRET=${{secrets.USER_SECRET}} -e ADMIN_SECRET=${{secrets.ADMIN_SECRET}} -e API_OPENAI=${{secrets.API_OPENAI}} -e CLOUDINARY_URL=${{secrets.CLOUDINARY_URL}} ${{ secrets.DOCKERHUB_USERNAME }}/mipro
